---
name: Check ontology

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: obolibrary/odklite
    steps:
      - uses: actions/checkout@v4
      - run: check-rdfxml cop.owl
